# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crk24lvi6-capi-aws
  namespace: crk24lvi6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crk24lvi6-capi-aws
subjects:
- kind: ServiceAccount
  name: crk24lvi6-capi-aws
